globals:
  seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

models:
  name: GroupVAE
  params:
    input_shape: [1, 64, 64]
    n_latents: 10
    beta: 1.0
    aggregation: argmax
    label_mode: multi

dataset:
  name: dsprites_full
  type: weak
  params:
    iterator_len: 19200000
    k: 1
    return_index: False

loader:
  batch_size: 64

optimizer:
  name: Adam
  params:
    lr: 0.0001

logging:
  validate_interval: 30000
