globals:
  seed: 1213

models:
  name: BetaVAE
  params:
    input_shape: [1, 64, 64]
    n_latents: 10
    beta: 16.0

dataset:
  name: dsprites_full
  type: unsupervised
  params:
    iterator_len: 20000

loader:
  batch_size: 64

optimizer:
  name: Adam
  params:
    lr: 0.001

training:
  epochs: 1000

logging:
  validate_interval: 100
