globals:
  seed: 1213

models:
  name: GroupVAE
  params:
    input_shape: [1, 64, 64]
    beta: 1.0
    n_latents: 10
    aggregation: label
    label_mode: single

dataset:
  name: dsprites_full
  params:
    seed: 0
    iterator_len: 20000
    k: 1
    return_index: True

loader:
  batch_size: 64

optimizer:
  name: Adam
  params:
    lr: 0.0001

training:
  epochs: 1000

logging:
  validate_interval: 100
